////////////////////////////////////////////////////////
// Copyright (c) Alejandro Kalnay                     //
// License: GNU GPLv3                                 //
////////////////////////////////////////////////////////

using NUnit.Framework;
using System;

namespace Determination.Demo
{
    public sealed class GuidProviderDemos
    {
        #region Person

        internal class Person
        {
            // This constructor will assign to the Guid property
            // a Guid generated by the system.
            // Person instances that were created with this constructor
            // can't test anything that depends on a specific Guid.
            public Person(string firstName, string lastName) : this(firstName, lastName, new GuidProvider())
            {
            }

            // This constructor will assign to the Guid property
            // a Guid provided by the developer.
            // Person instances that were created with this constructor
            // can test anything that depends on a specific Guid.
            public Person(string firstName, string lastName, IGuidProvider guidProvider)
            {
                FirstName = firstName;
                LastName = lastName;
                Guid = guidProvider.Value;
            }

            public string FirstName { get; }

            public string LastName { get; }

            public Guid Guid { get; }
        }

        #endregion Person

        [Test]
        [Category("2 - Demo - GuidProvider - Person Tests")]
        // This test assigns a predefined Guid while creating an instance
        // of the Person class.
        // The test verifies that the value of the Person's Guid property is
        // indeed the Guid assigned when the Person instance was created.
        public void WhenTheGuidPropertyOfAPersonInstanceIsRetrieved_ThenItsValueIsTheGuidAssignedDuringTheCreationOfTheInstance()
        {
            // A real program can allow the framework to assign the Guid by doing:
            // Person person = new Person("Jim", "Smith");
            Guid guid = new Guid("7A0908FB-D9F9-4A6D-8F95-EFE4DE3D5027");
            Person person = new Person("Jim", "Smith", GuidProviderStub.Create(guid));
            Assert.AreEqual(guid, person.Guid);     // Validate that the person's Guid
                                                    // is the pre-defined Guid value.
        }
    }
}
